#!/usr/bin/env zsh

export ZSH_DISABLE_COMPFIX=true
export ZSH="$HOME/.oh-my-zsh"
export DISABLE_AUTO_UPDATE=true
export DISABLE_UPDATE_PROMPT=true
zstyle ':omz:update' mode disabled
ZSH_THEME=""
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source "$ZSH/oh-my-zsh.sh"

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats '%F{yellow} [%b]%f'
zstyle ':vcs_info:git:*' actionformats '%F{yellow} [%b|%a]%f'
precmd_functions+=(vcs_info)

PS1='%F{red}%B%n@%m%b%f%F{yellow}:%f%F{red}%B%~%b%f${vcs_info_msg_0_}%F{yellow}\$%f '

LS_COLORS="di=38;2;255;200;80:fi=38;2;220;220;220:ex=38;2;255;180;60:ln=38;2;120;200;255:so=38;2;180;140;255:bd=38;2;255;120;120:cd=38;2;255;160;80"
export LS_COLORS

typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[command]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#00FFFF,bold'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red,bold'

alias ll='ls -lahF --color=auto'
alias la='ls -la --color=auto'
alias ls='ls --color=auto'

cd_func() {
    if [[ $# -eq 0 ]]; then
        builtin cd "$HOME"
    else
        builtin cd "$@"
    fi
}
alias cd='cd_func'

HISTSIZE=10000
SAVEHIST=10000
setopt INC_APPEND_HISTORY

setopt COMPLETE_IN_WORD
setopt ALWAYS_TO_END
unsetopt FLOW_CONTROL

builtin cd "$HOME" 2>/dev/null
